- user-core/src/main/resources/application.yml
- user-core/src/main/resources/logback-spring.xml
- 하위 모듈에서 루트 프로젝트를 의존하지 못하기 때문에 구성 정보를 불러 올 수 없는 문제
- 커스텀 설정 클래스를 사용해도 해당 모듈의 컴포넌트 스캔을 하지 못하는 문제
- 하위 모듈에 루트 프로젝트와 동일한 실행 환경 설정
- application.yml
- logback-spring.xml
> [#27] 하위 모듈 테스트 시 구성 정보를 불러 오지 못하는 문제 해결

- src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
- 회원가입 로직의 트랜잭션 격리 수준을 REPEATABLE_READ에서 SERIALIZABLE로 격상
- 이메일 주소, 사용자 이름, 전화번호의 중복 검사 수행 중 다른 사용자가 동일 데이터로 가입하는 문제 방지
- 로그인 로직에 로그인 시간 업데이트 작업이 추가되었으므로 readOnly 속성 제거
- 누락된 전체 메서드의 트랜잭션 격리 수준 설정 설정(READ_COMMITTED) 추가
- 이메일 주소 변경과 전화번호 변경 로직에 중복된 이메일 주소와 전화번호에 대한 검사 과정 추가
- 트랜잭션 격리 수준을 REPEATABLE_READ로 격상
- 회원 데이터의 일관성 보장
- 중복 검사 도중 다른 사용자가 가입한 경우(phantom read) 변경 불가
> [#84] 회원 서비스 비즈니스 로직의 트랜잭션 격리 수준 조정

- src/main/java/com/firstone/greenjangteo/product/domain/dto/ProductDto.java
- src/main/java/com/firstone/greenjangteo/product/domain/model/Product.java
- src/main/java/com/firstone/greenjangteo/product/service/ProductService.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/controller/StoreController.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/dto/StoreProductDto.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/dto/StoreRequestDto.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/dto/StoreResponseDto.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/model/entity/Store.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/service/StoreService.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/service/StoreServiceImpl.java
- src/test/java/com/firstone/greenjangteo/user/domain/store/controller/StoreControllerTest.java
- src/test/java/com/firstone/greenjangteo/user/domain/store/service/StoreServiceTest.java
- src/test/java/com/firstone/greenjangteo/user/domain/store/testutil/TestObjectFactory.java
- Product 엔티티에 store 필드 추가
- Store 엔티티에 products 필드 추가
- 기타 두 도메인을 연결하기 위한 수정
- 상품 목록을 포함한 가게 조회에 대한 테스트 코드 추가
- 상품 도메인 코드의 변경을 최소화하면서 매핑하는 방향으로 진행
> [#95] 가게 엔티티와 상품 엔티티 매핑

- src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
- src/main/java/com/firstone/greenjangteo/user/controller/UserController.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/controller/StoreController.java
- src/main/java/com/firstone/greenjangteo/user/dto/request/UserIdRequestDto.java
- src/main/java/com/firstone/greenjangteo/web/ApiConstant.java
- src/test/java/com/firstone/greenjangteo/user/model/entity/UserTest.java
- src/test/java/com/firstone/greenjangteo/user/model/security/PasswordTest.java
- USER_ID_FORM의 상수명을 USER_ID_VALUE로 변경
- UserTest와 PasswordTest를 H2 데이터베이스에서 진행하도록 변경
- UserIdRequestDto에 Swagger 안내 문구 추가
> [#124] 상수명 변경 등 리팩토링

- src/main/java/com/firstone/greenjangteo/order/model/OrderProducts.java
- src/main/java/com/firstone/greenjangteo/order/model/entity/Order.java
- src/main/java/com/firstone/greenjangteo/order/service/OrderServiceImpl.java
- src/test/java/com/firstone/greenjangteo/order/model/OrderProductsTest.java
- src/test/java/com/firstone/greenjangteo/order/model/TotalOrderPriceTest.java
- 주문 도메인의 addOrder 메서드를 Order 클래스의 from 메서드 내부로  이동
- OrderServiceImpl 클래스의 createOrder 메서드에서 삭제
- OrderServiceImpl 클래스의 createOrderFromCart 메서드에서 삭제
- 주문 도메인 테스트 코드 수정
- TotalOrderPrice 클래스의 동등성 테스트 코드 추가
- OrderProductsTest 클래스의 일부 라인 개행
- 비즈니스 로직을 수행하는 메서드에 트랜잭션 적용
> [#127] 주문 도메인 리팩토링

- src/main/java/com/firstone/greenjangteo/order/dto/response/OrderResponseDto.java
- src/main/java/com/firstone/greenjangteo/order/dto/response/OrdersResponseDto.java
- src/main/java/com/firstone/greenjangteo/order/service/OrderServiceImpl.java
- src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
- src/main/java/com/firstone/greenjangteo/user/domain/store/dto/StoreResponseDto.java
- src/main/java/com/firstone/greenjangteo/user/dto/request/PhoneRequestDto.java
- src/main/java/com/firstone/greenjangteo/user/dto/response/SignInResponseDto.java
- src/main/java/com/firstone/greenjangteo/user/dto/response/SignUpResponseDto.java
- src/main/java/com/firstone/greenjangteo/user/form/SignUpForm.java
- src/main/java/com/firstone/greenjangteo/user/model/Role.java
- src/main/java/com/firstone/greenjangteo/user/model/embedment/Roles.java
- src/main/java/com/firstone/greenjangteo/user/model/entity/User.java
- src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
- src/test/java/com/firstone/greenjangteo/user/model/embedment/RolesTest.java
- 데이터 형식 일관성을 위해 DTO 클래스들의 시간 값 직렬화, 역직렬화 과정의 포맷 변환 프로세스 추가
- Roles 클래스의 메서드명 변경
- Role enum의 isSeller() 메서드 삭제
- User 클래스의 어노테이션 순서 조정
- SignUpForm 클래스의 Roles 예시 상수에 관리자 추가
- UserResponseDto 클래스의 userId 필드, of 메서드 삭제
- SignUpResponseDto 클래스 추가, 회원 가입 시 응답 객체 분리
- SignInResponseDto 클래스의 ID 필드명을 userId로 변경
- PhoneRequestDto 클래스의 예시 값 수정
> [#132] 프로젝트 전반적인 리팩토링

- src/main/java/com/firstone/greenjangteo/application/job/DeleteExpiredCouponJobConfig.java
- src/main/java/com/firstone/greenjangteo/application/scheduler/JobScheduler.java
- src/main/java/com/firstone/greenjangteo/coupon/repository/CouponRepository.java
- src/main/java/com/firstone/greenjangteo/coupon/service/CouponService.java
- src/main/java/com/firstone/greenjangteo/coupon/service/CouponServiceImpl.java
- src/test/java/com/firstone/greenjangteo/application/job/DeleteExpiredCouponJobConfigTest.java
- src/test/java/com/firstone/greenjangteo/coupon/repository/CouponRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/coupon/service/CouponServiceTest.java
- src/test/java/com/firstone/greenjangteo/coupon/testutil/CouponTestObjectFactory.java
- 매일 오전 6시에 실행되도록 스케줄러 설정
- JobScheduler 클래스에서 CouponService 인터페이스의 deleteExpiredCoupons 메서드 호출
- CouponServiceImpl 클래스의 removeCoupons 메서드에서 deleteExpiredCouponJob을 통한 쿠폰 일괄 삭제 로직 수행
- 유효기간 만료일 기반의 쿠폰 데이터 검색
- 유효기간 만료일이 deleteExpiredCouponJob 실행 날짜와 일치하는 쿠폰들에 대한 쿠폰 삭제 작업 수행
- deleteExpiredCouponJob 실행
- JobParameters를 통한 deleteExpiredCouponJob 실행
- CouponServiceImpl 클래스의 deleteExpiredCoupons 메서드 로직 수행
- 유효기간 만료일 기반의 쿠폰 데이터 검색
- 쿠폰 일괄 삭제 작업 수행
> [#162] 유효기간 만료 시 쿠폰 일괄 삭제 기능 추가

- src/main/java/com/firstone/greenjangteo/configuration/CacheConfig.java
- src/main/java/com/firstone/greenjangteo/hibernate/HibernateCollectionIdResolver.java
- src/main/java/com/firstone/greenjangteo/hibernate/HibernateCollectionMixIn.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/model/entity/Image.java
- src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java
- src/main/java/com/firstone/greenjangteo/user/model/Username.java
- src/main/java/com/firstone/greenjangteo/user/model/entity/User.java
- 게시글에서 사용되지 않는 정보를 담고 있는 포장 객체들을 직렬화 과정에서 제외하기 위해 JsonIgnore 어노테이션 적용
- Username 객체를 역직렬화하기 위해 JsonCreator와 JsonProperty 어노테이션 적용
- lastLoggedInAt 필드에 JsonSerialize와 JsonDeserialize 어노테이션 적용
- Post 엔티티의 images 필드에 JsonManagedReference 어노테이션 적용
- Image 엔티티의 post 필드에 JsonBackReference 어노테이션 적용
- HibernateCollectionMixIn 클래스를 통해 HibernateCollectionIdResolver 클래스 등록
- CacheConfig 클래스의 objectMapper 메서드를 통해 HibernateCollectionMixIn 클래스 등록
- redisCacheManage 메서드를 통해 GenericJackson2JsonRedisSerializer에 적용
> [#203] Redis Cache 적용 시 발생하는 직렬화, 역직렬화 문제 해결

- src/main/java/com/firstone/greenjangteo/post/controller/PostController.java
- src/main/java/com/firstone/greenjangteo/post/domain/view/model/entity/View.java
- src/main/java/com/firstone/greenjangteo/post/domain/view/model/service/ViewRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/view/model/service/ViewService.java
- src/main/java/com/firstone/greenjangteo/post/dto/PostResponseDto.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/view/model/service/ViewServiceTest.java
- View 엔티티
- 게시글 조회 시 조회 수 증가 로직 호출
- 조회 수 증가 비즈니스 로직
- 조회 수 증가 후 반환
- PostServiceImpl 클래스의 getPost 메서드에 readOnly 옵션 추가
- 게시글 조회 시 조회 수 증가 로직 호출,  반환
- 조회 수 증가 비즈니스 로직
> [#207] 게시글 조회 수 기능 추가

- src/main/java/com/firstone/greenjangteo/coupon/controller/CouponGroupController.java
- src/main/java/com/firstone/greenjangteo/post/aop/PostLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/post/controller/PostController.java
- src/main/java/com/firstone/greenjangteo/post/domain/view/model/service/ViewService.java
- src/main/java/com/firstone/greenjangteo/post/dto/PostsResponseDto.java
- src/main/java/com/firstone/greenjangteo/post/repository/PostRepository.java
- src/main/java/com/firstone/greenjangteo/post/service/PostService.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- src/main/java/com/firstone/greenjangteo/utility/FormatConverter.java
- src/main/java/com/firstone/greenjangteo/utility/PagingConstant.java
- src/test/java/com/firstone/greenjangteo/coupon/controller/CouponGroupControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/service/ImageServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/view/model/service/ViewServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/repository/PostRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/utility/PostTestConstant.java
- 전체 게시글 목록 조회 요청
- 전체 게시글 목록 조회 비즈니스 로직
- 전체 게시글 목록을 페이징 처리하고 생성 순서 내림차순으로 정렬해 조회
- 각 게시물의 조회 수 조회 비즈니스 로직
- 페이징 옵션을 별도의 클래스 상수로 분리
- FormatConverter 클래스 추가
- 정렬 방식 정보를 파싱하는 메서드를 별도의 클래스로 분리
- 전체 게시글 목록 조회 요청, 200 status code 응답
- 전체 게시글 목록 조회 비즈니스 로직
- 전체 게시글 목록을 페이징 처리하고 생성 순서 내림차순으로 정렬해 조회
- 각 게시물의 조회 수 조회 비즈니스 로직
> [#209] 전체 게시글 목록 조회 기능 추가

- src/main/java/com/firstone/greenjangteo/aop/LoggingAspect.java
- src/main/java/com/firstone/greenjangteo/coupon/controller/CouponGroupController.java
- src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupService.java
- src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceImpl.java
- src/main/java/com/firstone/greenjangteo/post/controller/PostController.java
- src/main/java/com/firstone/greenjangteo/post/repository/PostRepository.java
- src/main/java/com/firstone/greenjangteo/post/service/PostService.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- src/test/java/com/firstone/greenjangteo/coupon/controller/CouponGroupControllerTest.java
- src/test/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/repository/PostRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java
- 자신의 게시글 목록 조회 요청
- 자신의 게시글 목록 조회 비즈니스 로직
- 자신의 게시글 목록을 페이징 처리하고 생성 순서 내림차순으로 정렬해 조회
- 페이징과 ID를 매개변수로 갖는 비즈니스 로직의 로깅 추가
- 자신의 게시글 목록 조회 요청, 200 status code 응답
- 자신의 게시글 목록 조회 비즈니스 로직
- 자신의 게시글 목록을 페이징 처리하고 생성 순서 내림차순으로 정렬해 조회
> [#211] 자신의 게시글 목록 조회 기능 추가

- build.gradle
- src/main/java/com/firstone/greenjangteo/configuration/CacheConfig.java
- src/main/java/com/firstone/greenjangteo/post/repository/PostRepository.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- 게시글 등록 요청의 Cache key 이름에 게시자 ID를 포함하도록 표현식 수정
- 게시글 조회 요청의 Cache key 이름에 게시자 ID를 포함하도록 표현식 수정
- hibernate 5 module 의존성 추가
- hibernate 5 module을 object mapper에 등록
> [#213] [#214] Redis Cache를 통한 게시글 조회 문제 해결

- src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java
> [#216] Redis Cache를 통한 게시글 조회에서 이미지 목록을 불러 오지 못하는 문제 해결

- src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java
- PostLoad 어노테이션을 통해 Post 엔티티를 로드할 때 연관된 Image 엔티티 목록을 초기화하도록 설정
- PostLoad 어노테이션을 통해 Post 엔티티를 로드할 때 연관된 User 엔티티 목록을 초기화하도록 설정
> [#216] [#217] Redis Cache를 통해 조회 시 연관된 엔티티를 로드하지 못하는 문제 해결

- src/main/java/com/firstone/greenjangteo/post/controller/PostController.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/dto/ImageRequestDto.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/model/repository/ImageRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/repository/ImageRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/service/ImageService.java
- src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java
- src/main/java/com/firstone/greenjangteo/post/service/PostService.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/model/repository/ImageRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/service/ImageServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/testutil/ImageTestObjectFactory.java
- src/test/java/com/firstone/greenjangteo/post/domain/view/model/service/ViewServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/repository/PostRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java
- 게시글 수정 요청
- 게시글 수정 비즈니스 로직
- 이미지 수정 비즈니스 로직
- 게시글 ID를 통한 이미지 데이터 ID 오름차순 검색
- 게시글 ID를 통한 이미지 데이터 삭제
- 이미지 엔티티 목록을 통한 이미지 데이터 삭제
- 게시글 수정 요청, 200 status code 응답
- 게시글 수정 비즈니스 로직
- 이미지 수정 비즈니스 로직
- 게시글 ID를 통한 이미지 데이터 ID 오름차순 검색
- 게시글 ID를 통한 이미지 데이터 삭제
- 이미지 엔티티 목록을 통한 이미지 데이터 삭제
-  Post 도메인의 이름을 게시글로 통일
- ImageRepository 인터페이스의 패키지 이동
> [#220] 게시글 수정 기능 추가

- src/main/java/com/firstone/greenjangteo/post/aop/CommentLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/post/aop/ImageLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/controller/CommentController.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/dto/CommentRequestDto.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/dto/CommentResponseDto.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/model/entity/Comment.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/repository/CommentRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentService.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceImpl.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/model/entity/Image.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/service/ImageService.java
- src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java
- src/main/java/com/firstone/greenjangteo/post/service/PostService.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/controller/CommentControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentTestObjectFactory.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/service/ImageServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java
- 댓글 등록 요청
- 댓글 등록 요청 비즈니스 로직
- 게시글 ID를 통한 게시글 조회
- 댓글 데이터 저장
- 댓글에 포함된 이미지 목록 저장
- 201 status code 반환
- 비즈니스 로직의 로깅 AOP 추가
- 댓글 등록
- 이미지 목록 저장
- 댓글 등록 요청, 201 status code 응답
- 댓글 등록 비즈니스 로직
- 게시글 ID를 통한 게시글 조회
- 이미지 목록 저장 비즈니스 로직
> [#225] 댓글 등록 기능 추가

- src/main/java/com/firstone/greenjangteo/post/domain/comment/exception/message/NotFoundExceptionMessage.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/repository/CommentRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentService.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceImpl.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/repository/CommentRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceTest.java
- 댓글 조회 비즈니스 로직
- 댓글 ID와 작성자 ID를 통해 댓글 조회
- 일치하지 않는 댓글 또는 작성자 ID를 통한 조회 시 예외 처리
- 댓글 조회 비즈니스 로직
- 댓글 ID와 작성자 ID를 통해 댓글 조회
- 일치하지 않는 댓글 또는 작성자 ID를 통한 조회 시 예외 처리
> [#231] 댓글 조회 기능 추가

- src/main/java/com/firstone/greenjangteo/post/domain/comment/controller/CommentController.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/exception/message/InconsistentExceptionMessage.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/exception/serious/InconsistentCommentException.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/model/entity/Comment.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentService.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceImpl.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/repository/ImageRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/image/service/ImageService.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/controller/CommentControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentTestObjectFactory.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/model/repository/ImageRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/service/ImageServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/image/testutil/ImageTestObjectFactory.java
- 댓글 수정 요청
- 댓글 수정 비즈니스 로직
- 수정하려는 댓글의 게시글 ID가 일치하지 않는 경우에 대한 예외 처리
- 이미지 수정 비즈니스 로직
- 댓글 ID를 통한 이미지 데이터 ID 오름차순 검색
- 댓글 ID를 통한 이미지 데이터 삭제
- 이미지 엔티티 목록을 통한 이미지 데이터 삭제
- 댓글 수정 요청, 200 status code 응답
- 댓글 수정 비즈니스 로직
- 수정하려는 댓글 또는 작성자의 ID가 잘못된 경우에 대한 예외 처리
- 수정하려는 댓글의 게시글 ID가 일치하지 않는 경우에 대한 예외 처리
- 이미지 수정 비즈니스 로직
- 댓글 ID를 통한 이미지 데이터 ID 오름차순 검색
- 댓글 ID를 통한 이미지 데이터 삭제
- 이미지 엔티티 목록을 통한 이미지 데이터 삭제
> [#233] 댓글 수정 기능 추가

- src/main/java/com/firstone/greenjangteo/post/domain/comment/controller/CommentController.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/repository/CommentRepository.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentService.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceImpl.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/controller/CommentControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/repository/CommentRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceTest.java
- src/test/java/com/firstone/greenjangteo/post/domain/comment/service/CommentTestObjectFactory.java
- 댓글 삭제 요청
- 댓글 삭제 비즈니스 로직
- 댓글 ID와 회원 ID를 통해 댓글 존재 여부 확인
- 댓글 ID 또는 회원 ID가 일치하지 않는 경우 예외 처리
- 댓글 삭제 요청, 204 status code 응답
- 댓글 삭제 비즈니스 로직
- 댓글 ID와 회원 ID를 통해 댓글 존재 여부 확인
- 댓글 ID 또는 회원 ID가 일치하지 않는 경우 예외 처리
> [#235] 댓글 삭제 기능 추가

- src/main/java/com/firstone/greenjangteo/reserve/aop/ReserveLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/reserve/controller/ReserveController.java
- src/main/java/com/firstone/greenjangteo/reserve/dto/request/AddReserveRequestDto.java
- src/main/java/com/firstone/greenjangteo/reserve/exception/message/InvalidExceptionMessage.java
- src/main/java/com/firstone/greenjangteo/reserve/exception/message/NotFoundExceptionMessage.java
- src/main/java/com/firstone/greenjangteo/reserve/model/CurrentReserve.java
- src/main/java/com/firstone/greenjangteo/reserve/model/entity/ReserveHistory.java
- src/main/java/com/firstone/greenjangteo/reserve/repository/ReserveHistoryRepository.java
- src/main/java/com/firstone/greenjangteo/reserve/service/ReserveService.java
- src/main/java/com/firstone/greenjangteo/reserve/service/ReserveServiceImpl.java
- src/test/java/com/firstone/greenjangteo/reserve/controller/ReserveControllerTest.java
- src/test/java/com/firstone/greenjangteo/reserve/model/CurrentReserveTest.java
- src/test/java/com/firstone/greenjangteo/reserve/model/entity/ReserveHistoryTest.java
- src/test/java/com/firstone/greenjangteo/reserve/repository/ReserveHistoryRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/reserve/service/ReserveServiceTest.java
- src/test/java/com/firstone/greenjangteo/reserve/testutil/ReserveTestConstant.java
- src/test/java/com/firstone/greenjangteo/reserve/testutil/ReserveTestObjectFactory.java
- 적립금 추가 요청
- 적립금 내역(ReserveHistory) 엔티티 추가
- 적립금 추가 요청 비즈니스 로직
- 새로운 적립금 내역 생성
- 기존의 적립금에 적립금 추가
- 회원 ID를 통한 가장 최신의 적립금 내역 조회
- 201 status code 반환
- 비즈니스 로직의 로깅 AOP 추가
- 적립금 추가
- 적립금 추가 요청, 201 status code 응답
- 적립금 내역(ReserveHistory) 엔티티 생성
- 현재 적립금(CurrentReserve) 객체 생성
- 현재 적립금 객체에 적립금 추가
- 현재 적립금 액수에 대한 유효성 검사
- 적립금 추가 요청 비즈니스 로직
- 새로운 적립금 내역 생성
- 기존의 적립금에 적립금 추가
- 회원 ID를 통한 가장 최신의 적립금 내역 조회
> [#239] 적립금 추가 기능 추가

- src/main/java/com/firstone/greenjangteo/coupon/exception/serious/NotUsedCouponException.java
- src/main/java/com/firstone/greenjangteo/coupon/model/entity/Coupon.java
- src/main/java/com/firstone/greenjangteo/coupon/service/CouponService.java
- src/main/java/com/firstone/greenjangteo/coupon/service/CouponServiceImpl.java
- src/main/java/com/firstone/greenjangteo/order/controller/OrderController.java
- src/main/java/com/firstone/greenjangteo/order/excpeption/message/InvalidExceptionMessage.java
- src/main/java/com/firstone/greenjangteo/order/service/OrderService.java
- src/main/java/com/firstone/greenjangteo/order/service/OrderServiceImpl.java
- src/test/java/com/firstone/greenjangteo/coupon/service/CouponServiceTest.java
- src/test/java/com/firstone/greenjangteo/order/controller/OrderControllerTest.java
- src/test/java/com/firstone/greenjangteo/order/service/OrderServiceTest.java
- 쿠폰 사용 취소 요청
- 쿠폰 사용 취소 요청 비즈니스 로직
- 쿠폰에서 주문 ID 제거
- 아직 사용되지 않은 쿠폰일 시 예외 처리
- 주문에서 사용된 쿠폰 금액 제거
- 쿠폰 사용 취소 요청, 200 status code 응답
- 쿠폰 사용 취소 요청 비즈니스 로직
- 쿠폰에서 주문 ID 제거
- 아직 사용되지 않은 쿠폰일 시 예외 처리
- 주문에서 사용된 쿠폰 금액 제거
> [#248] 주문 쿠폰 사용 취소 기능 추가

- src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
- src/main/java/com/firstone/greenjangteo/user/domain/token/model/entity/RefreshToken.java
- src/main/java/com/firstone/greenjangteo/user/domain/token/repository/RefreshTokenRepository.java
- src/main/java/com/firstone/greenjangteo/user/domain/token/service/TokenService.java
- src/main/java/com/firstone/greenjangteo/user/dto/response/SignInResponseDto.java
- src/main/java/com/firstone/greenjangteo/user/security/JwtTokenProvider.java
- src/test/java/com/firstone/greenjangteo/user/controller/AuthenticationControllerTest.java
- src/test/java/com/firstone/greenjangteo/user/domain/token/service/TokenServiceTest.java
- 로그인 시 엑세스 토큰 발급 요청 비즈니스 로직
- 로그인 시 리프레시 토큰 발급 요청 비즈니스 로직
- JwtTokenProvider 클래스에서 리프레시 토큰 생성
- 생성된 리프레시 토큰 데이터 저장
- 로그인 시 엑세스 토큰 발급 요청 비즈니스 로직
- 로그인 시 리프레시 토큰 발급 요청 비즈니스 로직
> [#263] 로그인 시 리프레시 토큰 발급 기능 추가

- src/main/java/com/firstone/greenjangteo/user/domain/token/controller/TokenController.java
- src/main/java/com/firstone/greenjangteo/user/domain/token/model/entity/RefreshToken.java
- src/main/java/com/firstone/greenjangteo/user/domain/token/repository/RefreshTokenRepository.java
- src/main/java/com/firstone/greenjangteo/user/domain/token/service/TokenService.java
- src/test/java/com/firstone/greenjangteo/user/domain/token/controller/TokenControllerTest.java
- src/test/java/com/firstone/greenjangteo/user/domain/token/repository/RefreshTokenRepositoryTest.java
- src/test/java/com/firstone/greenjangteo/user/domain/token/service/TokenServiceTest.java
- src/test/java/com/firstone/greenjangteo/user/domain/token/testutil/TokenTestObjectFactory.java
- 리프레시 토큰을 통한 엑세스 토큰 재발급 요청
- 엑세스 토큰 재발급 요청 비즈니스 로직
- 리프레시 토큰 값을 통한 리프레시 토큰 튜플 검색
- 잘못된 리프레시 토큰 값을 통한 검색 시 예외 처리
- 201 status code 반환
- 엑세스 토큰 재발급 요청, 201 status code 응답
- 엑세스 토큰 재발급 요청 비즈니스 로직
- 리프레시 토큰 값을 통한 리프레시 토큰 튜플 검색
- 존재하지 않는 리프레시 토큰 값을 통한 검색 시 예외 처리
> [#264] 리프레시 토큰을 통한 엑세스 토큰 재발급 기능 추가

- src/main/java/com/firstone/greenjangteo/aop/LoggingAspect.java
- src/main/java/com/firstone/greenjangteo/configuration/WebSecurityConfig.java
- src/main/java/com/firstone/greenjangteo/coupon/aop/CouponLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/order/aop/OrderLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/order/dto/request/OrderProductRequestDto.java
- src/main/java/com/firstone/greenjangteo/post/aop/PostLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/post/domain/comment/service/CommentServiceImpl.java
- src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
- src/main/java/com/firstone/greenjangteo/user/aop/UserLoggingAspect.java
- src/main/java/com/firstone/greenjangteo/user/model/entity/User.java
- src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
- src/main/java/com/firstone/greenjangteo/user/service/UserServiceImpl.java
- src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
- src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java
- src/test/java/com/firstone/greenjangteo/user/controller/AuthenticationControllerTest.java
- User 엔티티에 게시판 목록에 대한 참조 추가
- AuthenticationServiceImpl 클래스와 UserServiceImpl 클래스의 일부 id 변수명을 userId로 변경
- AuthenticationControllerTest 클래스의 signInUser 메서드에서 SignUpForm 객체를 SignInForm 객체로 변경
- 사용자 인증 대상에서 /token 리소스 제외
- OrderProductRequestDto 클래스의 QUANTITY_EXAMPLE 상수의 접근 제한자를 default로 변경
- PostServiceImpl 클래스의 EntityNotFound 예외 처리 부분 개행
- PostControllerTest 클래스
- CommentService에 대한 참조 추가
- WithMocker 어노테이션에 username과 roles 추가
- PostServiceTest 클래스
- deletePost 메서드의 매개변수 변경
- deletePostWithWrongPostOrUserId 메서드 추가
- 사용하지 않는 import문 제거
- 각 도메인의 AOP 로그 출력 형식 통일
> [#267] 프로젝트 전반적인 리팩토링
