zerobase-first-one/green-jangteo-backend

.dockerignore
Dockerfile
Jenkinsfile
check-and-restart.sh
deploy.sh
set-up-docker.sh

- Configuration Files
- Jenkinsfile
- Dockerfile
- Shell Scripts
- set-up-docker.sh
- deploy.sh -
- check-and-restart.sh
- Jenkins Pipeline: http://my-jenkins.duckdns.org:8080/job/green-jangteo/

[#1] CI/CD 파이프라인 구축

---

build.gradle
src/main/java/com/firstone/greenjangteo/configuration/AuditConfig.java
src/main/java/com/firstone/greenjangteo/configuration/SwaggerConfig.java

- Swagger 설정 추가
- Audit 설정 추가
- 하위 모듈 설정 추가

[#3] 프로젝트 공통 설정 파일 추가

---

build.gradle
settings.gradle
user-api/build.gradle

- user-api 모듈
- 루트 프로젝트에 user-api 의존성
- user-api build 설정

[#8] 회원 도메인 개발을 위해 회원 api 모듈 추가

---

set-up-docker.sh

[#11] Shell Script 수정

---

common/src/main/java/com/firstone/greenjangteo/common/audit/BaseEntity.java

[#15] BaseEntity 클래스 추가

---

Jenkinsfile

[#23] 파이프라인의 typo 수정

---

Dockerfile
check-and-restart.sh
deploy.sh
src/main/resources/application.yml

[#7] SSL/TLS 인증서 복사 작업 추가

---

common/src/main/java/com/firstone/greenjangteo/common/exception/AbstractGeneralException.java
common/src/main/java/com/firstone/greenjangteo/common/exception/AbstractSeriousException.java
common/src/main/java/com/firstone/greenjangteo/common/exception/AbstractSignificantException.java
common/src/main/java/com/firstone/greenjangteo/common/exception/ErrorResponse.java
common/src/main/java/com/firstone/greenjangteo/common/exception/GlobalExceptionHandler.java

- Exception Handler
- 주로 발생하는 공통 예외 처리
- 각 모듈에서 상속 받아 사용할 수 있는 info, warn, error 레벨의 추상 클래스
- 에러 코드
- 에러 메시지

[#28] 공통 예외 처리를 위한 Exception Handler 추가

---

user-core/src/test/java/com/firstone/greenjangteo/user/testconfig/AuditConfig.java

- user-core 모듈
- AuditContig 클래스
##해결 과정
- AuditConfig 클래스를 하위 모듈의 test 모듈에 추가 해 테스트 환경에서의 JPA auditing 적용 문제 해결
- 등록시간, 수정시간 적용 테스트

[#32] 하위 모듈의 테스트 환경에서 루트 프로젝트의 설정이 적용되지 않는 문제 수정

---

README.md
src/main/java/com/firstone/greenjangteo/configuration/SwaggerConfig.java

[#34] README, Swagger 문서 추가

---

build.gradle
user-api/build.gradle

- user-api
- user-core 모듈
- user-trans 모듈
- root project
- validation
- lombok
- JPA
- redis
- sub projects
- validation
- user-api
- common 모듈

[#36] 의존성 추가, 사용하지 않는 의존성 제거

---

common/src/main/java/com/firstone/greenjangteo/common/exception/GlobalExceptionHandler.java
common/src/main/java/com/firstone/greenjangteo/common/exception/message/ExceptionLogMessage.java

- 예외처리 핸들러의 log 메시지를 상수화
- 예외처리 핸들러의 메서드 순서를 info - warn - error 순에서 error- warn - info로 변경

[#42] 예외처리 로깅에 대한 리팩토링

---

src/main/resources/application.yml

[#50] UserRepository가 DI Container에 중복으로 등록되는 문제 해결

---

user-api/src/main/java/com/firstone/greenjangteo/user/controller/UserController.java
user-api/src/main/java/com/firstone/greenjangteo/user/model/EntityToDtoMapper.java
user-api/src/test/java/com/firstone/greenjangteo/user/controller/UserControllerTest.java

[#55] 회원 조회 기능 추가

---

user-api/src/main/java/com/firstone/greenjangteo/user/controller/ApiConstant.java
user-api/src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
user-api/src/main/java/com/firstone/greenjangteo/user/controller/UserController.java
user-api/src/test/java/com/firstone/greenjangteo/user/controller/AuthenticationControllerTest.java
user-core/src/main/java/com/firstone/greenjangteo/user/dto/EmailRequestDto.java
user-core/src/main/java/com/firstone/greenjangteo/user/model/entity/User.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationService.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
user-core/src/test/java/com/firstone/greenjangteo/user/service/AuthenticationServiceTest.java

- 이메일 주소 변경 요청
- 이메일 주소 변경 비즈니스 로직
- 이메일 주소 변경 요청, 204 status code 응답
- 이메일 주소 변경 비즈니스 로직

[#64] 이메일 주소 변경 기능 추가

---

user-api/src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
user-api/src/test/java/com/firstone/greenjangteo/user/controller/AuthenticationControllerTest.java
user-core/src/main/java/com/firstone/greenjangteo/user/dto/PhoneRequestDto.java
user-core/src/main/java/com/firstone/greenjangteo/user/model/entity/User.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationService.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
user-core/src/test/java/com/firstone/greenjangteo/user/service/AuthenticationServiceTest.java

resolve #65
- 전화번호 변경 요청
- 전화번호 변경 비즈니스 로직

[#65] 전화번호 변경 기능 추가

---

user-api/src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
user-api/src/test/java/com/firstone/greenjangteo/user/controller/AuthenticationControllerTest.java
user-core/src/main/java/com/firstone/greenjangteo/user/dto/PasswordRequestDto.java
user-core/src/main/java/com/firstone/greenjangteo/user/model/entity/User.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationService.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
user-core/src/test/java/com/firstone/greenjangteo/user/service/AuthenticationServiceTest.java

- 비밀번호 변경 요청
-  비밀번호 변경 비즈니스 로직
- 비밀번호 변경 요청, 204 status code 응답
- 비밀번호 변경 비즈니스 로직

#66 비밀번호 변경 기능 추가

---

user-core/src/main/java/com/firstone/greenjangteo/user/excpeption/message/BlankExceptionMessage.java
user-core/src/main/java/com/firstone/greenjangteo/user/excpeption/message/DuplicateExceptionMessage.java
user-core/src/main/java/com/firstone/greenjangteo/user/excpeption/message/NotFoundExceptionMessage.java

[#70] 예외 처리 메시지 수정

---

user-api/src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
user-api/src/test/java/com/firstone/greenjangteo/user/controller/AuthenticationControllerTest.java
user-core/src/main/java/com/firstone/greenjangteo/user/dto/DeleteRequestDto.java
user-core/src/main/java/com/firstone/greenjangteo/user/dto/PasswordUpdateRequestDto.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationService.java
user-core/src/main/java/com/firstone/greenjangteo/user/service/AuthenticationServiceImpl.java
user-core/src/test/java/com/firstone/greenjangteo/user/service/AuthenticationServiceTest.java

- 회원 탈퇴 요청
- 회원 탈퇴 비즈니스 로직
- PasswordRequestDto의 이름 수정, 회원 탈퇴 요청 DTO와 분리
- 회원 탈퇴 요청, 204 status code 응답
- 회원 탈퇴 비즈니스 로직
- 컨트롤러 테스트의 요청 메서드 수정

[#67] 회원 탈퇴 기능 추가

---

src/main/java/com/firstone/greenjangteo/cart/controller/CartController.java
src/main/java/com/firstone/greenjangteo/cart/domain/dto/CartProductDto.java
src/main/java/com/firstone/greenjangteo/cart/domain/model/Cart.java
src/main/java/com/firstone/greenjangteo/cart/service/CartService.java

**AS-IS**
- 불필요한 변수 및 주석 삭제
- 반환 객체 수정
- order 엔티티 참조 삭제
**TO-BE**
- 장바구니 요구사항 추가 반영

장바구니 엔티티 관련 오류 수정 반영

---

src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
src/main/java/com/firstone/greenjangteo/user/domain/store/controller/StoreController.java
src/main/java/com/firstone/greenjangteo/user/domain/store/dto/StoreDto.java
src/main/java/com/firstone/greenjangteo/user/domain/store/model/StoreName.java
src/main/java/com/firstone/greenjangteo/user/domain/store/model/entity/Store.java
src/main/java/com/firstone/greenjangteo/user/domain/store/repository/StoreRepository.java
src/main/java/com/firstone/greenjangteo/user/domain/store/service/StoreService.java
src/main/java/com/firstone/greenjangteo/user/domain/store/service/StoreServiceImpl.java
src/test/java/com/firstone/greenjangteo/user/domain/store/controller/StoreControllerTest.java
src/test/java/com/firstone/greenjangteo/user/domain/store/repository/StoreRepositoryTest.java
src/test/java/com/firstone/greenjangteo/user/domain/store/service/StoreServiceTest.java
src/test/java/com/firstone/greenjangteo/user/domain/store/service/model/StoreNameTest.java
src/test/java/com/firstone/greenjangteo/user/domain/store/service/model/entity/StoreTest.java
src/test/java/com/firstone/greenjangteo/user/domain/store/testutil/TestObjectFactory.java
src/test/java/com/firstone/greenjangteo/user/service/AuthenticationServiceTest.java

- Store와 StoreName 객체의 패키지 이동
- 다른 클래스들의 importing 반영

[#91] Store와 StoreName 객체의 패키지 이동

---

src/main/java/com/firstone/greenjangteo/user/controller/ApiConstant.java
src/main/java/com/firstone/greenjangteo/user/controller/AuthenticationController.java
src/main/java/com/firstone/greenjangteo/user/controller/UserController.java
src/main/java/com/firstone/greenjangteo/user/form/SignInForm.java
src/main/java/com/firstone/greenjangteo/user/form/SignUpForm.java
src/main/java/com/firstone/greenjangteo/user/model/Email.java
src/main/java/com/firstone/greenjangteo/user/model/FullName.java
src/main/java/com/firstone/greenjangteo/user/model/Phone.java
src/main/java/com/firstone/greenjangteo/user/model/Username.java
src/main/java/com/firstone/greenjangteo/user/model/embedment/Address.java
src/main/java/com/firstone/greenjangteo/user/model/security/Password.java
src/test/java/com/firstone/greenjangteo/user/controller/UserControllerTest.java
src/test/java/com/firstone/greenjangteo/user/model/EmailTest.java
src/test/java/com/firstone/greenjangteo/user/model/FullNameTest.java
src/test/java/com/firstone/greenjangteo/user/model/PhoneTest.java
src/test/java/com/firstone/greenjangteo/user/model/UsernameTest.java
src/test/java/com/firstone/greenjangteo/user/model/embedment/RolesTest.java
src/test/java/com/firstone/greenjangteo/user/model/security/PasswordTest.java
src/test/java/com/firstone/greenjangteo/user/repository/UserRepositoryTest.java
src/test/java/com/firstone/greenjangteo/user/service/UserDetailsServiceTest.java

- 개행 조정
- 어노테이션의 순서 조정
- 중복된 필드 삭제
- 비어 있는 값에 대한 유효성 검사를 수행하는 isEmpty() 메서드를 isBlank()로 변경
- 테스트 케이스 추가
- 테스트 클래스의 일부 변수명 변경
- 일부 테스트 케이스 변경

[#86] 회원 도메인의 일부 코드 조정

---

src/main/java/com/firstone/greenjangteo/order/controller/OrderController.java
src/main/java/com/firstone/greenjangteo/order/dto/DtoConstant.java
src/main/java/com/firstone/greenjangteo/order/dto/request/CartOrderRequestDto.java
src/main/java/com/firstone/greenjangteo/order/dto/request/OrderProductRequestDto.java
src/main/java/com/firstone/greenjangteo/order/dto/request/OrderRequestDto.java
src/main/java/com/firstone/greenjangteo/order/service/OrderService.java
src/main/java/com/firstone/greenjangteo/order/service/OrderServiceImpl.java
src/test/java/com/firstone/greenjangteo/order/service/OrderServiceTest.java
src/test/java/com/firstone/greenjangteo/order/testutil/OrderTestObjectFactory.java

- 장바구니 주문 요청
- 장바구니 주문 요청 비즈니스 로직
- 장바구니 주문 데이터 저장
- 201 status code 반환
- 장바구니 주문 비즈니스 로직
- 장바구니 주문 데이터 검색

[#112] 장바구니 주문 요청 기능 추가

---

src/main/java/com/firstone/greenjangteo/product/controller/ProductController.java
src/main/java/com/firstone/greenjangteo/product/domain/dto/ProductDto.java
src/main/java/com/firstone/greenjangteo/product/domain/model/Product.java
src/main/java/com/firstone/greenjangteo/product/service/ProductService.java

**AS-IS**
- 상품 관련 불필요한 메서드 삭제
- 불필요한 import 문 삭제
**TO-BE**
- ElasticSearch 검색 엔진 구축

상품 관련 코드 리팩터링

---

src/main/java/com/firstone/greenjangteo/user/domain/store/dto/StoreProductDto.java

- 가게 조회 요청의 StoreProductDto 객체 반환 값에 productId 필드 추가

[#137] 가게 조회 요청의 응답 데이터 추가

---

src/main/java/com/firstone/greenjangteo/application/job/CreateCouponJobConfig.java
src/main/java/com/firstone/greenjangteo/application/model/CouponGroupModel.java
src/main/java/com/firstone/greenjangteo/coupon/dto/IssueCouponsRequestDto.java
src/main/java/com/firstone/greenjangteo/coupon/model/entity/CouponGroup.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponServiceImpl.java
src/test/java/com/firstone/greenjangteo/coupon/controller/CouponControllerTest.java
src/test/java/com/firstone/greenjangteo/coupon/dto/IssueCouponsRequestDtoTest.java
src/test/java/com/firstone/greenjangteo/coupon/model/entity/CouponGroupTest.java
src/test/java/com/firstone/greenjangteo/coupon/model/entity/CouponTest.java
src/test/java/com/firstone/greenjangteo/coupon/repository/CouponGroupRepositoryTest.java
src/test/java/com/firstone/greenjangteo/coupon/service/CouponServiceTest.java
src/test/java/com/firstone/greenjangteo/coupon/testutil/CouponTestObjectFactory.java

- scheduledIssueDate 필드의 타입을 LocalDateTime에서 LocalDate로 변경

[#143] 쿠폰 그룹의 scheduledIssueDate 타입 변경

---

src/main/java/com/firstone/greenjangteo/application/job/CreateCouponJobConfig.java

- 새로운 작업 수행 시 beforeStep 단계에서 batchJobState를 초기화하도록 변경

[#145] 최초 이후의 새로운 배치 작업을 수행하지 못하는 문제 해결

---

src/main/java/com/firstone/greenjangteo/application/job/CreateCouponJobConfig.java
src/main/java/com/firstone/greenjangteo/application/listener/ContextRefreshedEventListener.java
src/main/java/com/firstone/greenjangteo/coupon/aop/CouponLoggingAspect.java
src/main/java/com/firstone/greenjangteo/coupon/controller/CouponController.java
src/main/java/com/firstone/greenjangteo/coupon/model/Amount.java
src/main/java/com/firstone/greenjangteo/coupon/model/ExpirationPeriod.java
src/main/java/com/firstone/greenjangteo/coupon/model/IssueQuantity.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponServiceImpl.java
src/main/resources/application.yml

- 일부 클래스들의 개행, 변수명 재설정
- CreateCouponConfig 클래스
- 로그 메시지 상수화
- Job 실행 시 식별을 위한 시간 값을 전달하므로,  incrementer 삭제
- 예외 발생 시 10번 재시도하도록 설정
- CouponController 클래스의 Swagger 설명에 쿠폰의 추가 발행 안내 문구 추가
- 포장 객체들의 필드에 final 한정자 추가
- CouponServiceImpl 클래스의 createCoupons 메서드에 ```@Override``` 어노테이션 추가
- batch 관련 애플리케이션 설정 변경
- 애플리케이션 실행 시 batch 작업을 시작하지 않도록 설정
- 설정된 job 이름을 NONE으로 변경
- CouponService의 createCoupons 메서드 로깅 추가
- CouponLoggingAspect 클래스 추가
- logAroundForIssueCouponsRequestDto 메서드 추가

[#147] 쿠폰 도메인 리팩토링

---

src/test/java/com/firstone/greenjangteo/application/job/CreateCouponJobConfigTest.java

- CreateCouponJobConfigTest 클래스 추가
- run 메서드 추가

[#149] CreateCouponJobConfig 클래스의 테스트 코드 추가

---

src/main/java/com/firstone/greenjangteo/application/job/CreateCouponJobConfig.java
src/main/java/com/firstone/greenjangteo/coupon/model/IssueQuantity.java
src/main/java/com/firstone/greenjangteo/coupon/model/entity/CouponGroup.java

- CreateCouponJobConfig 클래스에 발행 매수 업데이트 로직 추가
- CouponGroup 클래스에 발행 매수 업데이트 로직 추가
- IssueQuantity 클래스에 발행 매수 업데이트 로직 추가

[#151] 쿠폰 추가 생성 시 쿠폰 그룹의 발행 매수 업데이트 로직 추가

---

src/main/java/com/firstone/greenjangteo/cart/domain/dto/response/CartProductListResponseDto.java
src/main/java/com/firstone/greenjangteo/cart/service/CartService.java

**AS-IS**
- 장바구니 상품 조회 시 응답 데이터에 이미지 URL 및 상점 정보 추가
**TO-BE**
- 추가 요구사항 반영

장바구니 상품 조회 시 응답 데이터 추가 반환

---

src/main/java/com/firstone/greenjangteo/coupon/controller/CouponGroupController.java
src/main/java/com/firstone/greenjangteo/coupon/model/CouponGroupEntityToDtoMapper.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupService.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceImpl.java
src/test/java/com/firstone/greenjangteo/coupon/controller/CouponGroupControllerTest.java
src/test/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceTest.java

- 쿠폰 그룹 목록 조회 요청
- 쿠폰 그룹 목록 조회 비즈니스 로직
- 쿠폰 그룹 목록 조회 요청, 200 status code 응답
- 쿠폰 그룹 목록 조회 비즈니스 로직

[#174] 쿠폰 그룹 목록 조회 기능 추가

---

src/main/resources/application.yml

Reverts zerobase-first-one/green-jangteo-backend#173

Revert "ES 관련 설정 추가"

---

src/main/java/com/firstone/greenjangteo/coupon/controller/CouponGroupController.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupService.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceImpl.java
src/test/java/com/firstone/greenjangteo/coupon/controller/CouponGroupControllerTest.java
src/test/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceTest.java

- 쿠폰 그룹 삭제 요청
- 쿠폰 그룹 삭제 비즈니스 로직
- 비즈니스 로직 메서드에 트랜잭션 추가
- 쿠폰 그룹 삭제 요청, 204 status code 응답
- 쿠폰 그룹 삭제 비즈니스 로직

[#180] 쿠폰 그룹 삭제 기능 추가

---

src/main/java/com/firstone/greenjangteo/coupon/controller/CouponController.java
src/main/java/com/firstone/greenjangteo/coupon/excpeption/message/NotFoundExceptionMessage.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponService.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponServiceImpl.java
src/test/java/com/firstone/greenjangteo/coupon/controller/CouponControllerTest.java
src/test/java/com/firstone/greenjangteo/coupon/service/CouponServiceTest.java

- 쿠폰 삭제 요청
- 쿠폰 삭제 비즈니스 로직
- 쿠폰 삭제 요청, 204 status code 응답
- 쿠폰 삭제 비즈니스 로직

[#182] 쿠폰 삭제 기능 추가

---

src/main/java/com/firstone/greenjangteo/coupon/controller/CouponController.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceImpl.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponServiceImpl.java
src/main/java/com/firstone/greenjangteo/order/controller/OrderController.java
src/main/java/com/firstone/greenjangteo/order/service/OrderService.java
src/main/java/com/firstone/greenjangteo/order/service/OrderServiceImpl.java
src/test/java/com/firstone/greenjangteo/coupon/controller/CouponControllerTest.java
src/test/java/com/firstone/greenjangteo/coupon/controller/CouponGroupControllerTest.java
src/test/java/com/firstone/greenjangteo/order/controller/OrderControllerTest.java
src/test/java/com/firstone/greenjangteo/order/service/OrderServiceTest.java
src/test/java/com/firstone/greenjangteo/user/service/UserDetailsServiceTest.java

- GET 요청의 전송 데이터 형식을 Query Parameter로 변경
- 트랜잭션 적용 대상, 만료 시간 수정
- 쿠폰 목록 조회 요청 Swagger 안내 문구 상수의 세미콜론 제거

[#166] 프로젝트 전반적인 리팩토링

---

Dockerfile
set-up-docker.sh

**AS-IS**
- set-up-docker.sh 내 ES 관련 설정 추가
**TO-BE**
- 추가 요구사항 반영

set-up-docker 스크립트 es 설정 추가

---

src/main/java/com/firstone/greenjangteo/configuration/ElasticSearchConfig.java

**AS-IS**
- ElasticSearchConfig 호스트 설정
**TO-BE**
- 추가 요구사항 반영

Elasticsearch host 설정

---

set-up-docker.sh

**AS-IS**
- set-up-docker.sh 내 es-container 관련 커맨드 수정
**TO-BE**
- 추가 요구사항 반영

set-up-docker 내 es-container 관련 커맨드 수정

---

src/main/java/com/firstone/greenjangteo/configuration/ElasticSearchConfig.java

**AS-IS**
- ElasticSearch Host 설정
**TO-BE**
- 추가 요구사항 반영

fix(search): ES host 설정

---

set-up-docker.sh

**AS-IS**
- set-up-docker.sh 내 es-image, es-container 코드 분리
- set-up-docker.sh 내 ElasticSearch 관련 불필요한 코드 삭제
**TO-BE**
- 추가 요구사항 반영

ElasticSearch 관련 set-up-docker.sh 파일 내 스크립트 수정

---

src/main/java/com/firstone/greenjangteo/product/controller/ProductController.java
src/main/java/com/firstone/greenjangteo/product/service/ProductService.java

**AS-IS**
- get products paging 관련 수정
**TO-BE**
- 추가 요구사항 반영

상품 조회 시 페이징관련 수정

---

src/main/java/com/firstone/greenjangteo/product/exception/ErrorCode.java
src/main/java/com/firstone/greenjangteo/product/exception/ProductRelatedException.java
src/main/java/com/firstone/greenjangteo/product/service/ProductReviewService.java
src/main/java/com/firstone/greenjangteo/product/service/ProductService.java

**AS-IS**
- 상품 관련 예외처리 수정
**TO-BE**
- 추가 요구사항 반영

상품 관련 예외처리 수정

---

src/main/java/com/firstone/greenjangteo/cart/controller/CartController.java
src/main/java/com/firstone/greenjangteo/cart/domain/dto/response/AddCartProductResponseDto.java
src/main/java/com/firstone/greenjangteo/cart/domain/dto/response/CartProductListResponseDto.java
src/main/java/com/firstone/greenjangteo/cart/exception/CartException.java
src/main/java/com/firstone/greenjangteo/cart/exception/ErrorCode.java
src/main/java/com/firstone/greenjangteo/cart/service/CartService.java
src/main/java/com/firstone/greenjangteo/product/exception/ErrorCode.java
src/main/java/com/firstone/greenjangteo/product/exception/ProductRelatedException.java
src/main/java/com/firstone/greenjangteo/product/service/ProductReviewService.java
src/main/java/com/firstone/greenjangteo/product/service/ProductService.java

**AS-IS**
- 장바구니 상품 id 반환
- 장바구니 상품 관련 예외처리 추가
**TO-BE**
- 추가 요구사항 반영

장바구니 상품 예외처리 추가 및 데이터 추가 반환

---

src/main/java/com/firstone/greenjangteo/configuration/CacheConfig.java

[#202] Redis Cache 설정 적용

---

src/main/java/com/firstone/greenjangteo/post/controller/PostController.java
src/main/java/com/firstone/greenjangteo/post/exception/message/NotFoundExceptionMessage.java
src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java
src/main/java/com/firstone/greenjangteo/post/repository/PostRepository.java
src/main/java/com/firstone/greenjangteo/post/service/PostService.java
src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
src/test/java/com/firstone/greenjangteo/post/domain/image/testutil/ImageTestObjectFactory.java
src/test/java/com/firstone/greenjangteo/post/repository/PostRepositoryTest.java
src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java
src/test/java/com/firstone/greenjangteo/post/utility/PostTestObjectFactory.java

- 게시글 조회 요청
- 게시글 조회 비즈니스 로직
- 게시글 ID와 게시자 ID를 통한 게시글 데이터 검색
- 게시글 데이터 검색 예외처리
- Redis Cache 적용
- 게시글 조회 요청, 200 status code 응답
- 게시글 조회 비즈니스 로직
- 게시글 ID와 게시자 ID를 통한 게시글 데이터 검색
- 게시글 데이터 검색 예외처리

[#201] 게시글 조회 기능 추가

---

src/main/java/com/firstone/greenjangteo/post/model/entity/Post.java

[#217] Redis Cache를 통한 게시글 수정 후 조회 시 회원을 불러 오지 못하는 문제 해결

---

src/main/java/com/firstone/greenjangteo/post/controller/PostController.java
src/main/java/com/firstone/greenjangteo/post/repository/PostRepository.java
src/main/java/com/firstone/greenjangteo/post/service/PostService.java
src/main/java/com/firstone/greenjangteo/post/service/PostServiceImpl.java
src/test/java/com/firstone/greenjangteo/post/controller/PostControllerTest.java
src/test/java/com/firstone/greenjangteo/post/repository/PostRepositoryTest.java
src/test/java/com/firstone/greenjangteo/post/service/PostServiceTest.java

- 게시글 삭제 요청
- 게시글 삭제 비즈니스 로직
- 게시글 ID와 회원 ID를 통해 게시글 존재 여부 확인
- 게시글 삭제 요청, 204 status code 응답
- 게시글 삭제 비즈니스 로직
- 게시글 ID와 회원 ID를 통해 게시글 존재 여부 확인

[#223] 게시글 삭제 기능 추가

---

src/main/resources/application.yml

- 애플리케이션의 JPA DDL 자동 설정을 create에서 update로 변경

[#237] 애플리케이션 설정 변경

---

src/main/java/com/firstone/greenjangteo/reserve/controller/ReserveController.java
src/main/java/com/firstone/greenjangteo/reserve/dto/response/ReserveResponseDto.java
src/main/java/com/firstone/greenjangteo/reserve/repository/ReserveHistoryRepository.java
src/main/java/com/firstone/greenjangteo/reserve/service/ReserveService.java
src/main/java/com/firstone/greenjangteo/reserve/service/ReserveServiceImpl.java
src/test/java/com/firstone/greenjangteo/reserve/controller/ReserveControllerTest.java
src/test/java/com/firstone/greenjangteo/reserve/repository/ReserveHistoryRepositoryTest.java
src/test/java/com/firstone/greenjangteo/reserve/service/ReserveServiceTest.java

- 적립금 내역 조회 요청
- 적립금 내역 조회 비즈니스 로직
- 적립금 내역을 생성 순서 내림차순으로 정렬해 조회
- 적립금 내역 조회 요청, 200 status code 응답
- 적립금 내역 조회 비즈니스 로직
- 적립금 내역을 생성 순서 내림차순으로 정렬해 조회

[#243] 적립금 내역 조회 기능 추가

---

src/main/java/com/firstone/greenjangteo/reserve/controller/ReserveController.java
src/main/java/com/firstone/greenjangteo/reserve/service/ReserveService.java
src/main/java/com/firstone/greenjangteo/reserve/service/ReserveServiceImpl.java
src/test/java/com/firstone/greenjangteo/reserve/controller/ReserveControllerTest.java
src/test/java/com/firstone/greenjangteo/reserve/service/ReserveServiceTest.java

- 현재 적립금 조회 요청
- 적립금 내역 조회 요청, 200 status code 응답
- 가장 최신의 적립금 내역을 조회
- 회원 ID에 해당하는 적립금이 존재하지 않을 시 예외 처리

[#245] 현재 적립금 조회 기능 추가

---

src/main/java/com/firstone/greenjangteo/coupon/exception/message/AbnormalStateExceptionMessage.java
src/main/java/com/firstone/greenjangteo/coupon/exception/message/BlankExceptionMessage.java
src/main/java/com/firstone/greenjangteo/coupon/exception/message/InvalidExceptionMessage.java
src/main/java/com/firstone/greenjangteo/coupon/exception/message/NotFoundExceptionMessage.java
src/main/java/com/firstone/greenjangteo/coupon/exception/serious/AlreadyProvidedCouponException.java
src/main/java/com/firstone/greenjangteo/coupon/exception/serious/AlreadyUsedCouponException.java
src/main/java/com/firstone/greenjangteo/coupon/exception/serious/InconsistentCouponSizeException.java
src/main/java/com/firstone/greenjangteo/coupon/exception/serious/InsufficientRemainingQuantityException.java
src/main/java/com/firstone/greenjangteo/coupon/model/Amount.java
src/main/java/com/firstone/greenjangteo/coupon/model/ExpirationPeriod.java
src/main/java/com/firstone/greenjangteo/coupon/model/IssueQuantity.java
src/main/java/com/firstone/greenjangteo/coupon/model/entity/Coupon.java
src/main/java/com/firstone/greenjangteo/coupon/model/entity/CouponGroup.java
src/main/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceImpl.java
src/test/java/com/firstone/greenjangteo/coupon/model/AmountTest.java
src/test/java/com/firstone/greenjangteo/coupon/model/ExpirationPeriodTest.java
src/test/java/com/firstone/greenjangteo/coupon/model/IssueQuantityTest.java
src/test/java/com/firstone/greenjangteo/coupon/model/entity/CouponGroupTest.java
src/test/java/com/firstone/greenjangteo/coupon/model/entity/CouponTest.java
src/test/java/com/firstone/greenjangteo/coupon/service/CouponGroupServiceTest.java
src/test/java/com/firstone/greenjangteo/coupon/service/CouponServiceTest.java

- 패키지명 excpeption을 exception으로 수정

[#250] 패키지명 오타 수정

---

src/main/java/com/firstone/greenjangteo/coupon/controller/CouponController.java
src/test/java/com/firstone/greenjangteo/coupon/model/entity/CouponTest.java

- 컨트롤러의 COUPON_ID 상수 접근 제한자를 public으로 변경
- CouponTest 클래스의 addNotNullUser 메서드에서 AlreadyGivenCouponException의 예외 메시지 변경

[#259] 쿠폰 도메인 리팩토링

---

src/main/java/com/firstone/greenjangteo/order/controller/OrderController.java
src/main/java/com/firstone/greenjangteo/order/model/entity/Order.java
src/main/java/com/firstone/greenjangteo/order/service/OrderService.java
src/main/java/com/firstone/greenjangteo/order/service/OrderServiceImpl.java
src/main/java/com/firstone/greenjangteo/reserve/model/entity/ReserveHistory.java
src/main/java/com/firstone/greenjangteo/reserve/service/ReserveService.java
src/main/java/com/firstone/greenjangteo/reserve/service/ReserveServiceImpl.java
src/test/java/com/firstone/greenjangteo/order/controller/OrderControllerTest.java
src/test/java/com/firstone/greenjangteo/order/model/entity/OrderTest.java
src/test/java/com/firstone/greenjangteo/order/service/OrderServiceTest.java
src/test/java/com/firstone/greenjangteo/reserve/service/ReserveServiceTest.java

- 쿠폰 사용 요청
- 쿠폰 사용 요청 비즈니스 로직
- 쿠폰에 주문 ID 추가
- 이미 사용된 쿠폰일 시 예외 처리
- 주문에 사용된 쿠폰 금액 추가
- 쿠폰과 적립금의 총 사용 금액이 총 주문 금액을 초과할 시 예외 처리
- 쿠폰 사용 요청, 200 status code 응답
- 쿠폰 사용 요청 비즈니스 로직
- 쿠폰에 주문 ID 추가
- 이미 사용된 쿠폰일 시 예외 처리
- 주문에 사용된 쿠폰 금액 추가
- 쿠폰과 적립금의 총 사용 금액이 총 주문 금액을 초과할 시 예외 처리

[#261] 주문 시 적립금 사용 기능 추가
